import { StyleSheet } from "react-native";
import { C } from "../colors";
import common from "./common";

export const DIFF_COLOR = { 쉬움: "#16A34A", 보통: "#EA580C", 어려움: "#DC2626" };

export default StyleSheet.create({
  ...common,
  container: { flex: 1, backgroundColor: C.bg },
  header: { backgroundColor: C.surface, borderBottomWidth: 1, borderBottomColor: C.border, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  pageTitle: { fontSize: 20, fontWeight: "700", letterSpacing: -0.3, color: C.text },
  resultCount: { fontSize: 12, color: C.textMuted },
  searchBar: {
    flexDirection: "row", alignItems: "center", gap: 10,
    height: 48, marginTop: 10, paddingHorizontal: 14,
    backgroundColor: C.surface, borderRadius: 12, borderWidth: 1.5, borderColor: C.border,
  },
  searchInput: { flex: 1, fontSize: 14, color: C.text },
  catChip: {
    height: 34, paddingHorizontal: 16, borderRadius: 999,
    borderWidth: 1.5, borderColor: C.border, backgroundColor: C.surface,
    justifyContent: "center",
  },
  catChipActive: { backgroundColor: C.primary, borderColor: C.primary },
  catChipFavActive: { backgroundColor: "#FFF0F0", borderColor: "#FFAAAA" },
  catChipText: { fontSize: 13, fontWeight: "600", color: C.textSub },
  catChipTextActive: { color: "#fff" },
  catChipTextFavActive: { color: "#DC2626" },
  sectionTitleMain: { fontSize: 15, fontWeight: "700", color: C.text, letterSpacing: -0.2 },
  recoCard: {
    width: 138, backgroundColor: C.surface, borderRadius: 16,
    borderWidth: 1, borderColor: "rgba(255,107,53,0.35)",
    shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.07, shadowRadius: 10, elevation: 2,
  },
  recoVisual: {
    height: 88, backgroundColor: "#FFF7ED",
    alignItems: "center", justifyContent: "center",
    position: "relative",
    borderTopLeftRadius: 15, borderTopRightRadius: 15,
  },
  recoBookmarkBtn: {
    position: "absolute", top: 8, right: 8,
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.88)",
    alignItems: "center", justifyContent: "center",
    shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.12, shadowRadius: 4, elevation: 2,
  },
  recoMatchBadge: {
    position: "absolute", bottom: 7, left: 7,
    backgroundColor: "rgba(240,253,244,0.92)",
    borderWidth: 1, borderColor: "#BBF7D0",
    borderRadius: 999, paddingHorizontal: 7, paddingVertical: 2,
    maxWidth: "88%",
  },
  recoMatchBadgeText: { fontSize: 9, fontWeight: "700", color: "#16A34A" },
  recoInfo: { padding: 8, paddingHorizontal: 10, paddingBottom: 10, gap: 3 },
  recoName: { fontSize: 12, fontWeight: "700", color: C.text, lineHeight: 17 },
  recoMeta: { fontSize: 10, color: C.textMuted },
  recoMetaRow: { flexDirection: "row", alignItems: "center", gap: 3, flexWrap: "nowrap" },
  recoMetaText: { fontSize: 10, color: C.textMuted },
  recoMetaSep: { fontSize: 9, color: C.border },
  recoMetaRating: { fontSize: 10, fontWeight: "700", color: "#d97706" },
  recoHint: { fontSize: 10, fontWeight: "600", color: "#EA580C" },
  trendCard: {
    width: 148, backgroundColor: C.surface, borderRadius: 16,
    borderWidth: 1, borderColor: "rgba(255,107,53,0.2)",
    shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.07, shadowRadius: 10, elevation: 2,
  },
  trendVisual: {
    height: 92, backgroundColor: "#FFF0E8",
    alignItems: "center", justifyContent: "center",
    position: "relative",
    borderTopLeftRadius: 15, borderTopRightRadius: 15,
  },
  rankBadge: {
    position: "absolute", top: 7, left: 8, height: 20, paddingHorizontal: 7,
    borderRadius: 999, backgroundColor: "rgba(0,0,0,0.18)", justifyContent: "center",
  },
  rankBadgeTop: { backgroundColor: "#FF6B35" },
  rankText: { fontSize: 10, fontWeight: "800", color: "#fff" },
  flame: { position: "absolute", top: 5, right: 8, fontSize: 16 },
  trendInfo: { padding: 10, gap: 5 },
  trendName: { fontSize: 13, fontWeight: "700", color: C.text, lineHeight: 17 },
  trendCountBadge: {
    paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999,
    backgroundColor: C.primaryLt, borderWidth: 1, borderColor: "rgba(255,107,53,0.25)",
    alignSelf: "flex-start",
  },
  trendCountText: { fontSize: 10, color: C.primaryDark },
  trendTag: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 999, backgroundColor: C.bg, borderWidth: 1, borderColor: C.border },
  trendTagText: { fontSize: 10, fontWeight: "600", color: C.textSub },
  recipeCard: {
    flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10,
    backgroundColor: C.surface, borderRadius: 16, padding: 14,
    shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.07, shadowRadius: 10,
    elevation: 2, borderWidth: 1, borderColor: "rgba(0,0,0,0.04)",
  },
  cardMain: { flexDirection: "row", gap: 13, flex: 1 },
  cardThumb: {
    width: 56, height: 56, borderRadius: 12, backgroundColor: C.bg,
    alignItems: "center", justifyContent: "center",
  },
  cardBody: { flex: 1, gap: 3 },
  cardName: { fontSize: 15, fontWeight: "700", color: C.text, letterSpacing: -0.2 },
  cardIngredients: { fontSize: 12, color: C.textMuted },
  badgeRow: { flexDirection: "row", gap: 6, marginTop: 5, alignItems: "center" },
  badgeTime: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, backgroundColor: "#EEF3FF" },
  badgeTimeText: { fontSize: 11, fontWeight: "700", color: "#3B67E0" },
  badgeDiff: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  badgeDiffText: { fontSize: 11, fontWeight: "700" },
  heartWrap: { flexDirection: "column", alignItems: "center", gap: 2, flexShrink: 0 },
  heartBtn: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", marginTop: -2 },
  heartBtnActive: {},
  heartCount: { fontSize: 10, color: "#9CA3AF", fontWeight: "500", lineHeight: 12 },
  emptyState: { alignItems: "center", paddingVertical: 44, gap: 8 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "flex-end" },
  modalSheet: {
    backgroundColor: C.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20,
    maxHeight: "92%",
  },
  modalTopBar: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    paddingTop: 12, paddingBottom: 8, paddingHorizontal: 16,
    borderBottomWidth: 1, borderBottomColor: C.border,
  },
  modalHandle: { width: 36, height: 4, borderRadius: 999, backgroundColor: C.border },
  modalCloseBtn: {
    position: "absolute", right: 14,
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: C.bg, alignItems: "center", justifyContent: "center",
  },
  recipeHeader: { flexDirection: "row", gap: 16, paddingBottom: 18 },
  recipeEmoji: {
    width: 72, height: 72, borderRadius: 16, backgroundColor: C.bg,
    alignItems: "center", justifyContent: "center",
  },
  recipeName: { fontSize: 18, fontWeight: "800", color: C.text, letterSpacing: -0.4, marginBottom: 6 },
  recipeIngr: { fontSize: 12, color: C.textMuted, lineHeight: 18, marginTop: 4 },
  divider: { height: 1, backgroundColor: C.border, marginVertical: 2 },
  sectionTitle: { fontSize: 13, fontWeight: "700", color: C.textMuted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 14 },
  stepItem: { flexDirection: "row", gap: 12, marginBottom: 10 },
  stepNumber: {
    width: 24, height: 24, borderRadius: 12, backgroundColor: C.primary,
    alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1,
  },
  stepNumberText: { fontSize: 11, fontWeight: "800", color: "#fff" },
  stepText: { flex: 1, fontSize: 14, lineHeight: 22, color: C.text },
  ytThumb: {
    width: "100%", aspectRatio: 16 / 9,
    backgroundColor: "#1a1a2e", borderRadius: 12,
    alignItems: "center", justifyContent: "center", marginBottom: 10, gap: 8,
  },
  ytPlayBtn: {
    width: 52, height: 52, borderRadius: 26, backgroundColor: "rgba(255,0,0,0.9)",
    alignItems: "center", justifyContent: "center",
  },
  ytLabel: { fontSize: 11, fontWeight: "700", color: "rgba(255,255,255,0.5)", letterSpacing: 1 },
  ytTitle: { fontSize: 13, fontWeight: "600", color: C.text, lineHeight: 20 },
  cardNameRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6 },
  cardRating: { flexDirection: "row", alignItems: "center", gap: 2, flexShrink: 0 },
  cardRatingText: { fontSize: 12, fontWeight: "700", color: "#d97706" },
  modalNameRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 6 },
  modalHeaderRating: { flexDirection: "row", alignItems: "center", gap: 3, flexShrink: 0 },
  modalHeaderRatingText: { fontSize: 14, fontWeight: "700", color: "#d97706" },
  reviewTitleRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 12 },
  reviewCountBadge: {
    minWidth: 20, height: 20, paddingHorizontal: 6, borderRadius: 999,
    backgroundColor: C.primaryLt, borderWidth: 1, borderColor: "rgba(255,107,53,0.25)",
    alignItems: "center", justifyContent: "center",
  },
  reviewCountText: { fontSize: 11, fontWeight: "700", color: C.primary },
  photoThumb: {
    width: 72, height: 72, borderRadius: 12,
    alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: "rgba(0,0,0,0.06)", flexShrink: 0, overflow: "hidden",
  },
  photoThumbMore: {
    position: "absolute", top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.52)", alignItems: "center", justifyContent: "center",
  },
  photoThumbMoreText: { fontSize: 14, fontWeight: "800", color: "#fff" },
  reviewItem: {
    flexDirection: "row", alignItems: "flex-start", gap: 12,
    paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: C.border,
  },
  reviewContent: { flex: 1, minWidth: 0, gap: 5 },
  reviewHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  reviewUser: { fontSize: 13, fontWeight: "700", color: C.text, flex: 1 },
  reviewStars: { flexDirection: "row", alignItems: "center", gap: 1, flexShrink: 0 },
  reviewText: { fontSize: 13, color: C.textSub, lineHeight: 20 },
  reviewPhoto: {
    width: 62, height: 62, borderRadius: 12, flexShrink: 0,
    alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: "rgba(0,0,0,0.05)",
  },
  textReviewItem: { paddingVertical: 12, borderTopWidth: 1, borderTopColor: C.border, gap: 6 },
  textReviewMeta: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  textReviewRightMeta: { flexDirection: "row", alignItems: "center", gap: 8, flexShrink: 0 },
  textReviewDate: { fontSize: 11, color: C.textMuted },
  reviewMoreBtn: {
    height: 42, marginTop: 12, borderWidth: 1.5, borderColor: C.border,
    borderRadius: 12, alignItems: "center", justifyContent: "center",
  },
  reviewMoreBtnText: { fontSize: 13, fontWeight: "600", color: C.textSub },
});
