import { StyleSheet } from "react-native";
import { C } from "../colors";
import common from "./common";

export default StyleSheet.create({
  ...common,
  container: { flex: 1, backgroundColor: C.bg, paddingHorizontal: 16, paddingTop: 20, paddingBottom: 4 },
  fridgeCard: {
    flex: 1, backgroundColor: C.surface, borderRadius: 16,
    borderWidth: 1, borderColor: "rgba(255,107,53,0.35)",
    shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.07, shadowRadius: 10,
    elevation: 3, overflow: "hidden",
  },
  cardHeader: {
    flexDirection: "row", alignItems: "center", gap: 8,
    padding: 14, backgroundColor: C.bg,
    borderBottomWidth: 1, borderBottomColor: C.border,
  },
  cardIcon: { fontSize: 20 },
  cardTitle: { fontSize: 15, fontWeight: "700", color: C.text, flex: 1 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6, flexShrink: 0 },
  addIngredientBtn: {
    flexDirection: "row", alignItems: "center", gap: 4,
    paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999,
    borderWidth: 1.5, borderColor: C.primary, backgroundColor: C.primaryLt,
  },
  addIngredientBtnText: { fontSize: 11, fontWeight: "700", color: C.primary },
  convenienceBtn: {
    flexDirection: "row", alignItems: "center", gap: 4,
    paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999,
    borderWidth: 1.5, borderColor: "#d97706", backgroundColor: "#fffbeb",
  },
  convenienceBtnText: { fontSize: 11, fontWeight: "700", color: "#b45309" },
  tabBar: { borderBottomWidth: 1, borderBottomColor: C.border, maxHeight: 56, flexGrow: 0 },
  tab: {
    paddingHorizontal: 14, paddingVertical: 6, borderRadius: 999,
    borderWidth: 1.5, borderColor: C.border,
  },
  tabActive: { backgroundColor: C.primary, borderColor: C.primary },
  tabUrgent: { borderColor: "#FCA5A5" },
  tabUrgentActive: { backgroundColor: "#DC2626", borderColor: "#DC2626" },
  tabText: { fontSize: 13, fontWeight: "600", color: C.textMuted },
  tabTextActive: { color: "#fff" },
  tabTextUrgent: { color: "#DC2626" },
  content: { flex: 1 },
  emptyState: { alignItems: "center", justifyContent: "center", paddingVertical: 44, gap: 8 },
  emptyIcon: { fontSize: 52 },
  emptyTitle: { fontSize: 15, fontWeight: "700", color: C.text },
  emptyDesc: { fontSize: 13, color: C.textMuted, textAlign: "center" },
  groupHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 },
  catBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 999, borderWidth: 1.5 },
  catBadgeText: { fontSize: 12, fontWeight: "700" },
  catCount: { fontSize: 12, color: C.textMuted },
  ingredientItem: {
    flexDirection: "row", alignItems: "center", gap: 10,
    backgroundColor: C.surface, borderRadius: 12, padding: 10,
    borderWidth: 1.5, borderColor: C.border,
    shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 1,
  },
  ingredientItemSelected: {
    borderColor: "#E67E5E", backgroundColor: "#fff5f2",
  },
  ingrPhoto: {
    width: 44, height: 44, borderRadius: 12, backgroundColor: C.bg,
    borderWidth: 1, borderColor: C.border, alignItems: "center", justifyContent: "center",
  },
  ingrBody: { flex: 1, gap: 3 },
  ingrName: { fontSize: 14, fontWeight: "500", color: C.text },
  expiryLabel: { fontSize: 11, fontWeight: "500" },
  countBadge: {
    paddingHorizontal: 9, paddingVertical: 3, borderRadius: 999,
    backgroundColor: C.primaryLt,
  },
  countBadgeText: { fontSize: 12, fontWeight: "700", color: C.primary },
  editBtn: {
    width: 26, height: 26, borderRadius: 6,
    borderWidth: 1, borderColor: C.border,
    alignItems: "center", justifyContent: "center",
  },
  removeBtn: {
    width: 28, height: 28, borderRadius: 14,
    alignItems: "center", justifyContent: "center",
  },
  removeBtnText: { fontSize: 18, color: C.textMuted },
  recipeSearchBtn: {
    marginTop: 10, marginBottom: 10,
    height: 46, borderRadius: 12,
    backgroundColor: C.primary,
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
    shadowColor: C.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8,
    elevation: 6,
  },
  recipeSearchBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  // edit bottom sheet
  editOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "flex-end" },
  editSheet: {
    backgroundColor: "#fff", borderRadius: 20,
    paddingHorizontal: 20, paddingTop: 12, paddingBottom: 24,
    gap: 16, alignItems: "center",
  },
  editSheetHandle: { width: 36, height: 4, backgroundColor: "#e5e7eb", borderRadius: 2, marginBottom: 4 },
  editSheetTitle: { fontSize: 15, fontWeight: "700", color: C.text, alignSelf: "center" },
  editSheetHeader: { width: "100%", flexDirection: "row", alignItems: "center", gap: 14 },
  editSheetEmoji: { fontSize: 36 },
  editSheetName: { fontSize: 17, fontWeight: "700", color: C.text },
  editSheetCat: { fontSize: 12, color: C.textMuted, marginTop: 2 },
  editSheetRow: {
    width: "100%", flexDirection: "row",
    alignItems: "center", justifyContent: "space-between",
  },
  editSheetLabel: { fontSize: 14, fontWeight: "600", color: C.text },
  countRow: { flexDirection: "row", alignItems: "center", gap: 16 },
  countBtn: {
    width: 38, height: 38, borderRadius: 19,
    borderWidth: 1.5, borderColor: C.border, backgroundColor: C.bg,
    alignItems: "center", justifyContent: "center",
  },
  countBtnText: { fontSize: 22, color: C.text, lineHeight: 26 },
  countDisplay: { fontSize: 20, fontWeight: "700", minWidth: 36, textAlign: "center", color: C.text },
  expiryGroup: { width: "100%", alignItems: "center", gap: 10 },
  expiryGroupLabel: { alignSelf: "flex-start", fontSize: 14, fontWeight: "600", color: C.text },
  dateInput: {
    width: "75%", height: 46, paddingHorizontal: 16,
    borderWidth: 1.5, borderColor: C.border,
    borderRadius: 12, fontSize: 14, color: C.text,
    textAlign: "center", backgroundColor: C.surface,
  },
  shortcutsRow: { flexDirection: "row", gap: 7, flexWrap: "wrap", justifyContent: "center" },
  shortcutBtn: {
    height: 32, paddingHorizontal: 13, borderRadius: 999,
    borderWidth: 1.5, borderColor: C.border, backgroundColor: C.surface,
    alignItems: "center", justifyContent: "center",
  },
  shortcutBtnText: { fontSize: 12, fontWeight: "700", color: C.textSub },
  editActions: { width: "100%", flexDirection: "row", gap: 10, marginTop: 8 },
  cancelBtn: {
    height: 46, paddingHorizontal: 18, borderWidth: 1.5, borderColor: C.border,
    borderRadius: 12, backgroundColor: "transparent",
    alignItems: "center", justifyContent: "center", flexShrink: 0,
  },
  cancelBtnText: { fontSize: 14, fontWeight: "700", color: C.textMuted },
  saveBtn: {
    flex: 1, height: 46, borderRadius: 12, backgroundColor: C.primary,
    alignItems: "center", justifyContent: "center",
  },
  saveBtnText: { fontSize: 14, fontWeight: "700", color: "#fff" },
});
